### ISSUE TITLE
Is this working with server side schema splitted in multiple ts files with gql tags ?

### ISSUE THREAD

**Issue by olup** [graphql/vscode-graphql#236]
## Actual Behavior
Nothing works, plus syntax error on closing bracket for type definition ("expecting name, saw }")

## Expected Behavior

I am not even sure server side is in this plugin's scope... but nice behaviour would be autocomplete from scalar types plus types defined in different schema's pieces. Maybe I have a misconfigured graphql-config. Have been trying globs on schema but I guess it's not supported yet. Should I use the server's url ?

## Steps to Reproduce the Problem Or Description

Set Up an apollo based graphql server with multiple typedefs files in ts format exporting gql tagged graphql pieces of schema

**Comment by acao** [comment]
yes it has autocomplete for all those things, you just need different configurations, and there is a known bug with this approach

**Comment by olup** [comment]
Is there configuration examples that I could use ?

Le mer. 7 oct. 2020 à 20:06, Rikki Schulte <notifications@github.com> a
écrit :

**Comment by acao** [comment]
it currently only works when schema files are identified individually because of a bug, so you'll have to use:

```yml
schema: 
  - src/schema/file.ts
  - src/schema/anotherFile.ts
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

and that last option to tell it to use files for schema definitions, rather than the generated SDL by default.

the other bug you might see is that the offset doesn't work for in-TS definitions, so when you jump to an SDL definition in a TS or JS file, it might not scroll to the proper line. its a regression caused by jsdoc comments it seems. very hard to test all the different edge cases!

**Comment by olup** [comment]
I guess. A big thanks for this anyway. I went back to code-first approach
with nexus on this one, but will try your setup as soon as I can.
