### ISSUE TITLE
[Feature Request]  Linting inside the gql-tag

### ISSUE THREAD

**Issue by guledali** [graphql/vscode-graphql#69]
![lint](https://user-images.githubusercontent.com/20647282/45912426-4c69cb00-be21-11e8-9cc5-bfb2452788b1.jpg)

**Comment by divyenduz** [comment]
For anyone who is interested in contributing:- https://github.com/divyenduz/ts-graphql-plugin/blob/master/src/graphql-language-service-proxy.ts#L125-L126

This is where we need to translate the incoming offset and replace the start, length fields. 

Feel free to reach out in case you want to pick this up. Otherwise, I will pick this up sometime in October :)

**Comment by guledali** [comment]
@divyenduz Any update on this one
